export type RootStackParamList = {
  Login: undefined;
  Register: { userType: 'tenant' | 'landlord' };
  UserType: undefined;
  LandlordHome: undefined;
  TenantHome: undefined;
  LandlordListings: undefined;
  LandlordChatbot: undefined;
  Inquiries: undefined;
  Chatbot: undefined;
  SavedItems: undefined;
  Search: undefined;
  Preview: undefined;
  PropertyDetails: { propertyId: string };
  AddProperty: { listingId?: string; additionalData?: { id: string } };
  EditProfile: undefined;
  Profile: undefined;
  ChangePassword: undefined;
  Notifications: undefined;
  errorBoundary: undefined;
  Home: undefined;
  Filter: undefined;
  VerifyEmail: { email: string };
}; 